#___________________________________________________________________________________________________
# Carga de librerías necesarias para evalpack
library(gtools)
library(stringr)

#___________________________________________________________________________________________________
# Funciones para corregir caracteres
source('R/corchar.R')

#___________________________________________________________________________________________________
# Función para leer funciones de utilidad que provienen del Logical Decision
source('R/funcion_utilidad.R')
